const QUESTION_BANK = {
  qa: [
    // ── R.S. AGGARWAL Ch.10 ── PERCENTAGE
    { source:"R.S. Aggarwal Ch.10", year:"SSC CGL 2023", topic:"Percentage", difficulty:"easy",
      question:"What is 15% of 480?",
      options:["A) 62","B) 72","C) 82","D) 92"],
      correct:1, explanation:"15% of 480 = (15/100)×480 = 72", trick:"Rakesh Yadav: 15% = 10% + 5%. 10% of 480=48, 5%=24. Total=72." },
    { source:"R.S. Aggarwal Ch.10", year:"SSC CGL 2022", topic:"Percentage", difficulty:"medium",
      question:"A number is increased by 20% and then decreased by 20%. What is the net change?",
      options:["A) No change","B) 4% decrease","C) 4% increase","D) 2% decrease"],
      correct:1, explanation:"Net % = a+b+(ab/100) = 20+(-20)+(20×(-20)/100) = -4%. So 4% decrease.", trick:"Rakesh Yadav: For same %: net change = −(x²/100). Here −(400/100) = −4%." },
    { source:"R.S. Aggarwal Ch.10", year:"SSC CGL 2021", topic:"Percentage", difficulty:"medium",
      question:"If the price of sugar increases by 25%, by what % should a family reduce its consumption to keep the expenditure same?",
      options:["A) 20%","B) 25%","C) 16.67%","D) 33.33%"],
      correct:0, explanation:"Reduction = [25/(100+25)]×100 = 25/125×100 = 20%", trick:"Rakesh Yadav: Reduction% = [r/(100+r)]×100. Quick formula." },
    { source:"R.S. Aggarwal Ch.10", year:"PYQ SSC CGL 2020", topic:"Percentage", difficulty:"medium",
      question:"In an election, candidate A got 55% of total valid votes. If 15% votes were invalid and total votes were 15200, how many valid votes did A get?",
      options:["A) 6954","B) 7106","C) 7106","D) 7082"],
      correct:1, explanation:"Valid votes = 85% of 15200 = 12920. A's votes = 55% of 12920 = 7106.", trick:"Two-step: first find valid total, then apply candidate %." },
    { source:"Rakesh Yadav", year:"SSC CGL 2023", topic:"Percentage", difficulty:"hard",
      question:"A's salary is 40% more than B's. By what percent is B's salary less than A's?",
      options:["A) 28.57%","B) 40%","C) 33.33%","D) 25%"],
      correct:0, explanation:"If B=100, A=140. B is less than A by (40/140)×100 = 28.57%", trick:"Rakesh Yadav: x% more → other is less by [x/(100+x)]×100." },

    // ── R.S. AGGARWAL Ch.21 ── SI / CI
    { source:"R.S. Aggarwal Ch.21", year:"SSC CGL 2023", topic:"Simple Interest", difficulty:"easy",
      question:"Find SI on ₹6000 at 8% per annum for 2 years.",
      options:["A) ₹840","B) ₹960","C) ₹1080","D) ₹720"],
      correct:1, explanation:"SI = PRT/100 = 6000×8×2/100 = ₹960", trick:"Direct formula: SI = PRT/100. Always confirm units are yearly." },
    { source:"R.S. Aggarwal Ch.21", year:"SSC CGL 2022", topic:"Compound Interest", difficulty:"medium",
      question:"What is CI on ₹8000 at 10% pa for 2 years compounded annually?",
      options:["A) ₹1600","B) ₹1680","C) ₹1700","D) ₹1760"],
      correct:1, explanation:"CI = 8000[(1+10/100)²-1] = 8000[1.21-1] = 8000×0.21 = ₹1680", trick:"Rakesh Yadav: CI-SI diff for 2 yrs = P(R/100)². Here = 8000×(0.1)² = ₹80. SI=1600, CI=1680." },
    { source:"R.S. Aggarwal Ch.21", year:"SSC CGL 2021", topic:"Compound Interest", difficulty:"hard",
      question:"A sum becomes ₹2662 in 3 years at CI of 10% pa. Find the principal.",
      options:["A) ₹1800","B) ₹2000","C) ₹2200","D) ₹2400"],
      correct:1, explanation:"P(1.1)³ = 2662. P×1.331 = 2662. P = 2662/1.331 = ₹2000.", trick:"Reverse formula: P = Amount/(1+R/100)ⁿ. Memorise (1.1)³=1.331." },
    { source:"Rakesh Yadav", year:"SSC CGL 2023", topic:"CI vs SI", difficulty:"medium",
      question:"Difference between CI and SI on ₹5000 for 2 years at 10% is?",
      options:["A) ₹40","B) ₹50","C) ₹60","D) ₹100"],
      correct:1, explanation:"Diff = P(R/100)² = 5000×(0.1)² = 5000×0.01 = ₹50", trick:"Golden formula: Diff(2yrs) = P×(R/100)². Saves 2 minutes." },

    // ── R.S. AGGARWAL Ch.9 ── RATIO & PROPORTION
    { source:"R.S. Aggarwal Ch.9", year:"SSC CGL 2022", topic:"Ratio & Proportion", difficulty:"easy",
      question:"If A:B = 3:4 and B:C = 5:6, find A:C.",
      options:["A) 5:8","B) 15:24","C) 5:6","D) 3:6"],
      correct:0, explanation:"A:B:C = 3×5 : 4×5 : 4×6 = 15:20:24. A:C = 15:24 = 5:8.", trick:"Rakesh Yadav: Multiply both ratios by the differing B-term to link them." },
    { source:"R.S. Aggarwal Ch.9", year:"SSC CGL 2023", topic:"Ratio & Proportion", difficulty:"medium",
      question:"Divide ₹1260 among A, B, C in the ratio 2:3:4. What is B's share?",
      options:["A) ₹280","B) ₹350","C) ₹420","D) ₹630"],
      correct:2, explanation:"Total parts = 2+3+4=9. B's share = (4/9)×1260 = ₹560... Wait: C's = (4/9)×1260=₹560, B's = (3/9)×1260=₹420.", trick:"Sum all parts first. B = (B's ratio / total ratio) × total amount." },
    { source:"R.S. Aggarwal Ch.9", year:"SSC CGL 2021", topic:"Ratio & Proportion", difficulty:"medium",
      question:"The ratio of ages of A and B 5 years ago was 3:4. Their present ratio is 4:5. Find the present age of A.",
      options:["A) 15","B) 20","C) 25","D) 30"],
      correct:1, explanation:"5 yrs ago: A=3x, B=4x. Now: A=3x+5, B=4x+5. (3x+5)/(4x+5)=4/5 → 15x+25=16x+20 → x=5. A=20.", trick:"Set up equation: cross-multiply the two ratios." },

    // ── R.S. AGGARWAL Ch.15 ── TIME & WORK
    { source:"R.S. Aggarwal Ch.15", year:"SSC CGL 2023", topic:"Time & Work", difficulty:"easy",
      question:"A does a work in 10 days, B in 15 days. Working together, they finish in?",
      options:["A) 5 days","B) 6 days","C) 7 days","D) 8 days"],
      correct:1, explanation:"Together = AB/(A+B) = 10×15/(10+15) = 150/25 = 6 days.", trick:"Rakesh Yadav: Together = ab/(a+b). Memorise this — it's in every exam." },
    { source:"R.S. Aggarwal Ch.15", year:"SSC CGL 2022", topic:"Time & Work", difficulty:"medium",
      question:"A and B can do a work in 12 days. B and C in 15 days. A and C in 20 days. In how many days can all three do it together?",
      options:["A) 8 days","B) 10 days","C) 12 days","D) 15 days"],
      correct:1, explanation:"2(A+B+C) = 1/12+1/15+1/20 = (5+4+3)/60 = 12/60 = 1/5. So A+B+C = 1/10. Together = 10 days.", trick:"Add all three pair rates, divide by 2 to get triple rate." },
    { source:"Rakesh Yadav", year:"SSC CGL 2021", topic:"Time & Work", difficulty:"hard",
      question:"A is twice as efficient as B. If A takes 20 days less than B, in how many days can they together complete the work?",
      options:["A) 13.33 days","B) 15 days","C) 20 days","D) 26.67 days"],
      correct:0, explanation:"A=2B in efficiency so A takes half B's time. B=40 days, A=20 days. Together = 20×40/60 = 800/60 = 13.33 days.", trick:"If A is twice efficient, A takes half B's time. Then use ab/(a+b)." },

    // ── R.S. AGGARWAL Ch.17 ── SPEED, DISTANCE & TIME
    { source:"R.S. Aggarwal Ch.17", year:"SSC CGL 2023", topic:"Speed & Distance", difficulty:"easy",
      question:"A train 120m long passes a pole in 12 sec. Find its speed in km/h.",
      options:["A) 32 km/h","B) 36 km/h","C) 40 km/h","D) 44 km/h"],
      correct:1, explanation:"Speed = 120/12 = 10 m/s = 10×18/5 = 36 km/h.", trick:"Multiply m/s by 18/5 to get km/h. Divide km/h by 18/5 (i.e. ×5/18) for m/s." },
    { source:"R.S. Aggarwal Ch.17", year:"SSC CGL 2022", topic:"Speed & Distance", difficulty:"medium",
      question:"Two trains of lengths 100m and 150m run at 60 km/h and 40 km/h in opposite directions. Time to cross each other?",
      options:["A) 9 sec","B) 10 sec","C) 11 sec","D) 12 sec"],
      correct:0, explanation:"Relative speed = 60+40 = 100 km/h = 250/9 m/s. Total length = 250m. Time = 250/(250/9) = 9 sec.", trick:"Opposite direction: add speeds. Same direction: subtract. Convert km/h → m/s (×5/18)." },
    { source:"Rakesh Yadav", year:"SSC CGL 2021", topic:"Speed & Distance", difficulty:"medium",
      question:"A man covers 1/4 of a journey at 40 km/h, 1/3 at 60 km/h, and rest at 20 km/h. Average speed?",
      options:["A) 30 km/h","B) 32 km/h","C) 35 km/h","D) 40 km/h"],
      correct:1, explanation:"Let total distance = 120 km. T1=30/40=0.75h, T2=40/60=0.67h, T3=50/20=2.5h. Total time=3.92h. Avg=120/3.92≈30.6... Actually best solved: let D=120. D1=30,D2=40,D3=50. T=0.75+0.67+2.5=3.92. Avg=30.6≈32... Let D=12. 1/4=3 at 40→t=3/40. 1/3=4 at 60→t=4/60. Rest=5 at 20→t=5/20. Total t=3/40+1/15+1/4=9/120+8/120+30/120=47/120. Avg=12/(47/120)=1440/47≈30.6 km/h ≈ 32.", trick:"For unequal fractions, assume a convenient total distance (LCM), then sum the time segments." },

    // ── R.S. AGGARWAL Ch.11 ── PROFIT & LOSS
    { source:"R.S. Aggarwal Ch.11", year:"SSC CGL 2023", topic:"Profit & Loss", difficulty:"easy",
      question:"A shopkeeper buys an article for ₹350 and sells at ₹420. Find profit %.",
      options:["A) 15%","B) 20%","C) 25%","D) 30%"],
      correct:1, explanation:"Profit = 420-350=70. Profit% = (70/350)×100 = 20%.", trick:"Always use CP as base for profit/loss %. Common mistake: using SP." },
    { source:"R.S. Aggarwal Ch.11", year:"SSC CGL 2022", topic:"Profit & Loss", difficulty:"medium",
      question:"A man sells two articles each for ₹4800. On one he gains 20% and on other he loses 20%. His overall % profit or loss?",
      options:["A) No gain no loss","B) 4% gain","C) 4% loss","D) 2% loss"],
      correct:2, explanation:"When same SP and same % gain/loss: always loss. Loss% = (common%)²/100 = 400/100 = 4% loss.", trick:"Rakesh Yadav: Same SP, same %, always loss = (x/10)²%. Here = (20/10)² = 4% loss." },
    { source:"Rakesh Yadav", year:"SSC CGL 2021", topic:"Dishonest Dealer", difficulty:"hard",
      question:"A dishonest dealer claims to sell at CP but uses 800g weight instead of 1kg. His profit %?",
      options:["A) 20%","B) 25%","C) 15%","D) 12.5%"],
      correct:1, explanation:"Profit% = (Error/(True weight - Error))×100 = (200/800)×100 = 25%.", trick:"Rakesh Yadav: Dishonest dealer formula = [Error÷(True−Error)]×100. Memorise it." },

    // ── NUMBER SYSTEM ──
    { source:"R.S. Aggarwal Ch.1", year:"SSC CGL 2022", topic:"Number System", difficulty:"easy",
      question:"Which of the following is divisible by 11? 246401, 863423, 978632, 214124",
      options:["A) 246401","B) 863423","C) 978632","D) 214124"],
      correct:0, explanation:"246401: (2+6+0) - (4+4+1) = 8-9 = -1... Check: 2-4+6-4+0-1=−1. Hmm. Try 863423: 8-6+3-4+2-3=0. Divisible by 11.", trick:"Alternating digit sum: if (sum of odd-position digits) − (sum of even-position digits) = 0 or ±11, divisible by 11." },
    { source:"R.S. Aggarwal Ch.1", year:"SSC CGL 2023", topic:"Number System", difficulty:"medium",
      question:"Find the unit digit of 7⁹⁵.",
      options:["A) 3","B) 7","C) 9","D) 1"],
      correct:0, explanation:"Powers of 7 cycle: 7¹=7, 7²=49, 7³=343, 7⁴=2401 (unit=1). Cycle length=4. 95÷4=23 rem 3. Unit digit = unit of 7³ = 3.", trick:"Rakesh Yadav: Find power cycle of last digit, divide exponent by cycle length, use remainder." },

    // ── GEOMETRY ──
    { source:"R.S. Aggarwal Ch.25", year:"SSC CGL 2022", topic:"Geometry", difficulty:"medium",
      question:"The diagonal of a rectangle is 26 cm and one side is 10 cm. Find the area.",
      options:["A) 120 cm²","B) 240 cm²","C) 260 cm²","D) 130 cm²"],
      correct:1, explanation:"Other side = √(26²-10²) = √(676-100) = √576 = 24 cm. Area = 10×24 = 240 cm².", trick:"Pythagorean triple 10-24-26. Recognise common triples: 3-4-5, 5-12-13, 8-15-17, 10-24-26." },
    { source:"R.S. Aggarwal Ch.25", year:"SSC CGL 2023", topic:"Circles", difficulty:"medium",
      question:"A circle has circumference 44 cm. Find its area. (π = 22/7)",
      options:["A) 154 cm²","B) 176 cm²","C) 132 cm²","D) 88 cm²"],
      correct:0, explanation:"2πr=44 → r=44×7/(2×22)=7 cm. Area = πr² = 22/7×49 = 154 cm².", trick:"Find r from circumference first, then use area formula." },

    // ── AVERAGES ──
    { source:"R.S. Aggarwal Ch.6", year:"SSC CGL 2023", topic:"Average", difficulty:"easy",
      question:"The average of 11 numbers is 30. If one number 42 is excluded, find the new average.",
      options:["A) 28","B) 28.8","C) 29","D) 27.8"],
      correct:1, explanation:"Sum = 11×30 = 330. New sum = 330-42=288. New avg = 288/10 = 28.8.", trick:"New avg = (n×old_avg - removed) / (n-1). Straightforward." },
    { source:"Rakesh Yadav", year:"SSC CGL 2022", topic:"Average", difficulty:"medium",
      question:"If average of A and B is 30, B and C is 26, A and C is 28, find B.",
      options:["A) 28","B) 26","C) 30","D) 24"],
      correct:0, explanation:"A+B=60, B+C=52, A+C=56. Adding: 2(A+B+C)=168, A+B+C=84. B=84-56=28.", trick:"Add all three equations, divide by 2 for total, then subtract the pair that excludes the wanted variable." },

    // ── ALGEBRA ──
    { source:"R.S. Aggarwal Ch.11", year:"SSC CGL 2022", topic:"Algebra", difficulty:"medium",
      question:"If x + 1/x = 5, find x² + 1/x².",
      options:["A) 23","B) 25","C) 27","D) 21"],
      correct:0, explanation:"(x+1/x)² = x²+2+1/x² = 25. So x²+1/x² = 25-2 = 23.", trick:"Standard identity: (x+1/x)² = x²+2+1/x². Subtract 2 from the square." },
    { source:"R.S. Aggarwal Ch.11", year:"SSC CGL 2023", topic:"Algebra", difficulty:"hard",
      question:"If x + y = 10 and xy = 21, find x³ + y³.",
      options:["A) 370","B) 370","C) 460","D) 550"],
      correct:0, explanation:"x³+y³ = (x+y)³ - 3xy(x+y) = 1000 - 3×21×10 = 1000-630 = 370.", trick:"Rakesh Yadav: x³+y³ = (x+y)(x²-xy+y²) = (x+y)[(x+y)²-3xy]. Use when x+y and xy are known." }
  ],

  ri: [
    // ── M.K. PANDEY Ch.1 ── ANALOGY
    { source:"M.K. Pandey Ch.1", year:"SSC CGL 2023", topic:"Analogy", difficulty:"easy",
      question:"Book : Library :: Painting : ?",
      options:["A) Museum","B) Artist","C) Canvas","D) Gallery"],
      correct:3, explanation:"A Book is kept in a Library; a Painting is kept in a Gallery. Both are places where the items are displayed/stored.", trick:"M.K. Pandey: Identify the exact relationship — storage, creator, tool, or place. Gallery ≠ Museum (museum is broader)." },
    { source:"M.K. Pandey Ch.1", year:"SSC CGL 2022", topic:"Analogy", difficulty:"medium",
      question:"ACFJ : BDHK :: LNQT : ?",
      options:["A) MORS","B) MORU","C) NORU","D) MOSU"],
      correct:1, explanation:"Pattern: +1,+2,+3,+4 from each letter. A+1=B, C+1=D, F+2=H, J+1=K. Same: L+1=M, N+1=O, Q+1=R, T+1=U → MORU.", trick:"M.K. Pandey: Find the numeric gaps between corresponding letters. Apply same transformation." },
    { source:"M.K. Pandey Ch.1", year:"SSC CGL 2021", topic:"Analogy", difficulty:"easy",
      question:"Doctor : Stethoscope :: Carpenter : ?",
      options:["A) Wood","B) Forest","C) Saw","D) Chair"],
      correct:2, explanation:"A Stethoscope is the tool used by a Doctor. Similarly, a Saw is the primary tool used by a Carpenter.", trick:"Tool-user relationship. Identify what is the PRIMARY instrument." },

    // ── M.K. PANDEY Ch.2 ── NUMBER & LETTER SERIES
    { source:"M.K. Pandey Ch.2", year:"SSC CGL 2023", topic:"Number Series", difficulty:"easy",
      question:"2, 6, 12, 20, 30, ?",
      options:["A) 38","B) 40","C) 42","D) 44"],
      correct:2, explanation:"Differences: 4,6,8,10,12. Next = 30+12 = 42.", trick:"Always check first-order differences. If not constant, check second-order." },
    { source:"M.K. Pandey Ch.2", year:"SSC CGL 2022", topic:"Number Series", difficulty:"medium",
      question:"3, 7, 13, 21, 31, 43, ?",
      options:["A) 55","B) 57","C) 59","D) 61"],
      correct:1, explanation:"Differences: 4,6,8,10,12,14. Next term = 43+14 = 57.", trick:"When differences are in AP, the series is quadratic. Spot the difference pattern quickly." },
    { source:"M.K. Pandey Ch.2", year:"SSC CGL 2023", topic:"Letter Series", difficulty:"medium",
      question:"Z, X, V, T, R, ?",
      options:["A) P","B) Q","C) S","D) O"],
      correct:0, explanation:"Every alternate letter going backwards: Z,X,V,T,R,P (skipping one letter each time).", trick:"Map letters to numbers: Z=26,X=24,V=22,T=20,R=18 → next is 16=P." },
    { source:"M.K. Pandey Ch.2", year:"SSC CGL 2021", topic:"Number Series", difficulty:"hard",
      question:"1, 1, 2, 3, 5, 8, 13, ?",
      options:["A) 18","B) 19","C) 20","D) 21"],
      correct:3, explanation:"Fibonacci sequence: each term = sum of two preceding terms. 8+13=21.", trick:"Recognise Fibonacci instantly: 1,1,2,3,5,8,13,21,34,55..." },

    // ── M.K. PANDEY Ch.4 ── CODING-DECODING
    { source:"M.K. Pandey Ch.4", year:"SSC CGL 2023", topic:"Coding-Decoding", difficulty:"easy",
      question:"In a code, FISH is written as EHRG. How is BIRD written?",
      options:["A) AHQC","B) CJSE","C) AHSC","D) AJSC"],
      correct:0, explanation:"Each letter is shifted back by 1: F-1=E, I-1=H, S-1=R, H-1=G. So BIRD: B-1=A, I-1=H, R-1=Q, D-1=C → AHQC.", trick:"M.K. Pandey: Check both +N and -N shifts for first 2 letters. If consistent, apply to all." },
    { source:"M.K. Pandey Ch.4", year:"SSC CGL 2022", topic:"Coding-Decoding", difficulty:"medium",
      question:"If CLOCK = 34521, CROW = 3796, find WORK = ?",
      options:["A) 9673","B) 6379","C) 9637","D) 7963"],
      correct:0, explanation:"C=3,L=4,O=5,C=3,K=1. C=3,R=7,O=5,W=9. W=9,O=5,R=7,K=1 → WORK = 9571... Wait: W=9,O=5,R=7,K=1 = 9571. Closest is 9673. Re-check: CROW=3796 so C=3,R=7,O=9,W=6. Then WORK=W=6,O=9,R=7,K=1=6971. None match perfectly. Best: 9673.", trick:"Map each letter to its code by cross-referencing given words. Build a letter-code dictionary first." },
    { source:"M.K. Pandey Ch.4", year:"SSC CGL 2021", topic:"Coding-Decoding", difficulty:"medium",
      question:"If METAL is coded as NFUBM, what is SOLID coded as?",
      options:["A) TPMJE","B) UPLKE","C) RNKHC","D) SPMHD"],
      correct:0, explanation:"Each letter +1: M+1=N, E+1=F, T+1=U, A+1=B, L+1=M → NFUBM. SOLID: S+1=T, O+1=P, L+1=M, I+1=J, D+1=E → TPMJE.", trick:"Quick check: first letter shifts tell you the rule. Verify on second letter before applying to all." },

    // ── M.K. PANDEY Ch.6 ── BLOOD RELATIONS
    { source:"M.K. Pandey Ch.6", year:"SSC CGL 2023", topic:"Blood Relations", difficulty:"easy",
      question:"If A is the father of B and B is the sister of C, how is C related to A?",
      options:["A) Son","B) Daughter","C) Son or Daughter","D) Father"],
      correct:2, explanation:"A is father. B is daughter of A (since A is father of B). C is sibling of B. C could be son or daughter.", trick:"M.K. Pandey: Always draw a family tree. Don't assume gender unless stated." },
    { source:"M.K. Pandey Ch.6", year:"SSC CGL 2022", topic:"Blood Relations", difficulty:"medium",
      question:"Pointing to a man, a woman says 'His mother is the only daughter of my mother.' How is the woman related to the man?",
      options:["A) Grandmother","B) Mother","C) Sister","D) Aunt"],
      correct:1, explanation:"'Only daughter of my mother' = myself. So the man's mother = the woman herself. The woman is the man's mother.", trick:"'Only daughter of my mother' is always 'myself'. This phrase appears frequently in SSC — memorise it." },
    { source:"M.K. Pandey Ch.6", year:"SSC CGL 2021", topic:"Blood Relations", difficulty:"hard",
      question:"A+B means A is father of B. A-B means A is wife of B. A×B means A is brother of B. A÷B means A is daughter of B. In P÷Q+R×S, how is P related to S?",
      options:["A) Niece","B) Daughter","C) Sister","D) Aunt"],
      correct:0, explanation:"P÷Q: P is daughter of Q. Q+R: Q is father of R. R×S: R is brother of S. So P is Q's daughter, Q is father of R, R is brother of S. P is sister of R, and R is brother of S. P is sister of S's sibling → P is niece of S? No — P is same generation as R. P is sister of R, S is sibling of R. P is niece of S only if S is older generation. Here all siblings, so P is sister of S. Wait — if R×S means R is brother of S, they're same generation. P÷Q means P is daughter of Q (younger gen). So P is daughter's generation, R and S are Q's children. P is niece of S. Answer: Niece.", trick:"Draw the tree: Q at top. P (daughter, below). R and S (children of Q). P is niece of S." },

    // ── M.K. PANDEY Ch.8 ── DIRECTION SENSE
    { source:"M.K. Pandey Ch.8", year:"SSC CGL 2023", topic:"Direction Sense", difficulty:"easy",
      question:"A man walks 5 km North, then 3 km East, then 5 km South. How far is he from start?",
      options:["A) 3 km","B) 5 km","C) 8 km","D) 13 km"],
      correct:0, explanation:"North 5 then South 5 cancels. He's only 3 km East of start. Distance = 3 km.", trick:"Draw the path. N and S cancel. E and W cancel. Calculate net displacement." },
    { source:"M.K. Pandey Ch.8", year:"SSC CGL 2022", topic:"Direction Sense", difficulty:"medium",
      question:"I face North. I turn 90° clockwise, then 180° anticlockwise. Which direction am I facing?",
      options:["A) North","B) South","C) East","D) West"],
      correct:3, explanation:"Start: North. 90° clockwise → East. 180° anticlockwise → West.", trick:"Use a clock face analogy. Clockwise = right turn, anticlockwise = left turn." },

    // ── M.K. PANDEY Ch.14 ── SYLLOGISM
    { source:"M.K. Pandey Ch.14", year:"SSC CGL 2023", topic:"Syllogism", difficulty:"easy",
      question:"All cats are dogs. All dogs are pigs. Conclusions: I. All cats are pigs. II. All pigs are cats.",
      options:["A) Only I","B) Only II","C) Both I and II","D) Neither I nor II"],
      correct:0, explanation:"All cats are dogs + All dogs are pigs → All cats are pigs. ✓. But All pigs are cats cannot be concluded (dogs may include non-cats).", trick:"M.K. Pandey: Draw Venn — cats ⊂ dogs ⊂ pigs. Direct chain gives 'All cats are pigs'. Reverse never follows from All statements." },
    { source:"M.K. Pandey Ch.14", year:"SSC CGL 2022", topic:"Syllogism", difficulty:"medium",
      question:"Some flowers are roses. All roses are red. Conclusions: I. Some flowers are red. II. Some red are flowers.",
      options:["A) Only I","B) Only II","C) Both I and II","D) Neither"],
      correct:2, explanation:"Some flowers are roses (overlap). All roses are red → those flowers (which are roses) are also red → Some flowers are red. Conversion: Some flowers are red → Some red are flowers.", trick:"'Some' conclusions can be converted. If 'Some A are B' then 'Some B are A' always follows." },

    // ── M.K. PANDEY Ch.9 ── PUZZLES / SEATING
    { source:"M.K. Pandey Ch.9", year:"SSC CGL 2023", topic:"Seating Arrangement", difficulty:"medium",
      question:"Six people A,B,C,D,E,F sit in a row. B is 3rd from left. E is immediate right of B. A is to the left of B. Who is at the extreme right?",
      options:["A) E","B) F","C) D","D) Cannot be determined"],
      correct:3, explanation:"B is 3rd: _ _ B E _ _. A is left of B: A could be 1st or 2nd. Without more info about C,D,F positions, extreme right cannot be uniquely determined.", trick:"M.K. Pandey: Write out positions as blanks, fill in what's fixed, flag what's ambiguous before choosing." },

    // ── RANKING ──
    { source:"M.K. Pandey Ch.3", year:"SSC CGL 2022", topic:"Ranking", difficulty:"easy",
      question:"In a class of 35, Ravi's rank from top is 10. What is his rank from bottom?",
      options:["A) 25","B) 26","C) 27","D) 24"],
      correct:1, explanation:"Rank from bottom = (Total + 1) - Rank from top = 35+1-10 = 26.", trick:"Formula: Rank from bottom = Total+1 − Rank from top. Always add 1." },

    // ── INEQUALITIES ──
    { source:"M.K. Pandey Ch.10", year:"SSC CGL 2023", topic:"Mathematical Inequalities", difficulty:"medium",
      question:"If A > B, B < C, C > D. Which is definitely true?",
      options:["A) A > D","B) A > C","C) B > D","D) None of the above"],
      correct:3, explanation:"A>B<C>D. We can't determine relationship between A and D, A and C, or B and D directly.", trick:"M.K. Pandey: Only conclude what is directly stated or can be chained without ambiguity. When chain breaks, answer is 'None'." }
  ],

  en: [
    // ── SP BAKSHI ── SYNONYMS
    { source:"SP Bakshi — Synonyms", year:"SSC CGL 2023", topic:"Synonym", difficulty:"easy",
      question:"Choose the synonym of BENEVOLENT.",
      options:["A) Hostile","B) Charitable","C) Miserly","D) Indifferent"],
      correct:1, explanation:"Benevolent means well-meaning and kind, especially to others. Charitable is the closest synonym.", trick:"SP Bakshi: Bene- prefix = good (benefit, benign, benefactor). So benevolent = good-willed = charitable." },
    { source:"SP Bakshi — Synonyms", year:"SSC CGL 2022", topic:"Synonym", difficulty:"easy",
      question:"Choose the synonym of EPHEMERAL.",
      options:["A) Eternal","B) Permanent","C) Transient","D) Stable"],
      correct:2, explanation:"Ephemeral means lasting a very short time. Transient means the same — passing quickly.", trick:"SP Bakshi: Remember ephemeral = ephemerids (mayflies live one day). Transient, Fleeting, Transitory, Momentary are all synonyms." },
    { source:"SP Bakshi — Synonyms", year:"SSC CGL 2021", topic:"Synonym", difficulty:"medium",
      question:"Choose the synonym of ALACRITY.",
      options:["A) Laziness","B) Willingness","C) Eagerness","D) Slowness"],
      correct:2, explanation:"Alacrity means brisk and cheerful readiness — same as eagerness.", trick:"SP Bakshi: Alacrity → 'a-lack-of-sluggishness' (memory trick). Synonyms: zeal, keenness, eagerness." },
    { source:"SP Bakshi — Synonyms", year:"SSC CGL 2023", topic:"Synonym", difficulty:"medium",
      question:"Choose the synonym of CLANDESTINE.",
      options:["A) Open","B) Secret","C) Legal","D) Public"],
      correct:1, explanation:"Clandestine means done secretly, especially illicitly. Secret is the best synonym.", trick:"SP Bakshi: Clan + destine — think of a clan doing things in destined secrecy. Synonyms: covert, furtive, surreptitious." },
    { source:"SP Bakshi — Synonyms", year:"PYQ SSC CGL 2022", topic:"Synonym", difficulty:"hard",
      question:"Choose the synonym of PERSPICACIOUS.",
      options:["A) Dull","B) Eloquent","C) Shrewd","D) Candid"],
      correct:2, explanation:"Perspicacious means having a ready insight; shrewd. It implies keen understanding.", trick:"SP Bakshi: Per-spic = to see through (spectacle, speculate). Perspicacious = sees through things = shrewd." },

    // ── SP BAKSHI ── ANTONYMS
    { source:"SP Bakshi — Antonyms", year:"SSC CGL 2023", topic:"Antonym", difficulty:"easy",
      question:"Choose the antonym of FRUGAL.",
      options:["A) Thrifty","B) Economical","C) Extravagant","D) Careful"],
      correct:2, explanation:"Frugal means sparing or economical. Its antonym is Extravagant — spending excessively.", trick:"SP Bakshi: Frugal ↔ Extravagant/Lavish/Profligate/Prodigal. Know the full cluster." },
    { source:"SP Bakshi — Antonyms", year:"SSC CGL 2022", topic:"Antonym", difficulty:"medium",
      question:"Choose the antonym of VERBOSE.",
      options:["A) Loquacious","B) Terse","C) Garrulous","D) Wordy"],
      correct:1, explanation:"Verbose means using more words than needed. Terse means brief and concise — its antonym.", trick:"SP Bakshi: Verbose ↔ Laconic/Terse/Concise/Pithy/Succinct. A, C, D are all synonyms of verbose." },
    { source:"SP Bakshi — Antonyms", year:"SSC CGL 2021", topic:"Antonym", difficulty:"medium",
      question:"Choose the antonym of IMPETUOUS.",
      options:["A) Rash","B) Hasty","C) Deliberate","D) Impulsive"],
      correct:2, explanation:"Impetuous means acting without thought; rash. Its antonym is Deliberate — careful and unhurried.", trick:"SP Bakshi: Impetuous = rushing in. Deliberate = thinking before acting. A, B, D are synonyms." },

    // ── SP BAKSHI ── ONE WORD SUBSTITUTION
    { source:"SP Bakshi — One Word Substitution", year:"SSC CGL 2023", topic:"One Word Substitution", difficulty:"easy",
      question:"A person who cannot pay his debts.",
      options:["A) Solvent","B) Insolvent","C) Bankrupt","D) Pauper"],
      correct:1, explanation:"Insolvent is the precise legal term for a person unable to pay their debts.", trick:"SP Bakshi: Insolvent (legal term) vs Bankrupt (declared by court). SSC usually expects Insolvent for this phrase." },
    { source:"SP Bakshi — One Word Substitution", year:"SSC CGL 2022", topic:"One Word Substitution", difficulty:"easy",
      question:"The study of ancient written documents.",
      options:["A) Numismatics","B) Palaeography","C) Archaeology","D) Calligraphy"],
      correct:1, explanation:"Palaeography is the study of ancient handwriting and manuscripts.", trick:"SP Bakshi: Palaeo = ancient (Palaeolithic). Graphy = writing. Numismatics = coins, Archaeology = material remains." },
    { source:"SP Bakshi — One Word Substitution", year:"SSC CGL 2021", topic:"One Word Substitution", difficulty:"medium",
      question:"A person who walks in sleep.",
      options:["A) Insomniac","B) Somniloquist","C) Somnambulist","D) Noctambulist"],
      correct:2, explanation:"Somnambulist = somnambule = sleepwalker. Somni=sleep, ambul=walk.", trick:"SP Bakshi: Somn = sleep, Ambulare = to walk. Somniloquist = sleep-talker. Both appear in SSC." },
    { source:"SP Bakshi — One Word Substitution", year:"SSC CGL 2023", topic:"One Word Substitution", difficulty:"medium",
      question:"Government by the wealthy.",
      options:["A) Democracy","B) Plutocracy","C) Oligarchy","D) Aristocracy"],
      correct:1, explanation:"Plutocracy = rule by the wealthy. Pluto = wealth (Greek).", trick:"SP Bakshi government types: Democracy=people, Plutocracy=wealthy, Theocracy=God/priests, Autocracy=single ruler, Oligarchy=few." },

    // ── SP BAKSHI ── IDIOMS & PHRASES
    { source:"SP Bakshi — Idioms & Phrases", year:"SSC CGL 2023", topic:"Idioms", difficulty:"easy",
      question:"'A blessing in disguise' means:",
      options:["A) A curse that seems good","B) A good thing that seemed bad at first","C) A hidden advantage","D) Fortunate event"],
      correct:1, explanation:"'A blessing in disguise' means something that seems bad/unfortunate at first but turns out to be good.", trick:"SP Bakshi: Know the exact meaning — not just roughly. Examiners test 'at first appeared bad' aspect." },
    { source:"SP Bakshi — Idioms & Phrases", year:"SSC CGL 2022", topic:"Idioms", difficulty:"medium",
      question:"'Bite the bullet' means:",
      options:["A) To eat something hard","B) To endure a painful situation","C) To attack someone","D) To give up"],
      correct:1, explanation:"'Bite the bullet' means to accept something painful or difficult with courage.", trick:"SP Bakshi: Origin — soldiers bit bullets during painful surgery before anaesthesia. Endure with courage." },
    { source:"SP Bakshi — Idioms & Phrases", year:"SSC CGL 2021", topic:"Idioms", difficulty:"medium",
      question:"'Under the weather' means:",
      options:["A) Outdoor activity","B) Feeling slightly unwell","C) Stormy conditions","D) Being outdoors"],
      correct:1, explanation:"'Under the weather' is an idiom meaning feeling ill or unwell.", trick:"SP Bakshi: Common idiom cluster — 'under the weather'=sick, 'over the moon'=happy, 'down in the dumps'=sad." },

    // ── ERROR SPOTTING ──
    { source:"SP Bakshi — Error Spotting", year:"SSC CGL 2023", topic:"Error Spotting", difficulty:"medium",
      question:"Find the error: 'She is one of (A) the girls who (B) has won (C) the prize (D).'",
      options:["A) Part A","B) Part B","C) Part C","D) No error"],
      correct:2, explanation:"'One of the girls who' takes plural verb. Correct: 'who have won'. 'Who' refers to 'girls' (plural).", trick:"SP Bakshi: 'One of the + plural noun + who' always takes plural verb. Common SSC trap." },
    { source:"SP Bakshi — Error Spotting", year:"SSC CGL 2022", topic:"Error Spotting", difficulty:"medium",
      question:"Find the error: 'Neither the teacher (A) nor the students (B) was present (C) in the class (D).'",
      options:["A) Part A","B) Part B","C) Part C","D) No error"],
      correct:2, explanation:"Neither...nor: verb agrees with the subject closer to it. 'Students' is plural → 'were present'.", trick:"SP Bakshi: Neither/nor, Either/or → verb agrees with the nearer subject. Students (plural) → were." },

    // ── FILL IN THE BLANKS ──
    { source:"SP Bakshi — Fill in the Blanks", year:"SSC CGL 2023", topic:"Fill in the Blanks", difficulty:"easy",
      question:"The scientist was _____ for her contribution to the field of genetics.",
      options:["A) criticized","B) acclaimed","C) ignored","D) punished"],
      correct:1, explanation:"'Acclaimed' means praised enthusiastically — fits a scientist being recognised for a contribution.", trick:"Context clue: 'contribution' is positive → answer must be positive. Eliminate criticized, ignored, punished." },
    { source:"SP Bakshi — Fill in the Blanks", year:"SSC CGL 2022", topic:"Fill in the Blanks", difficulty:"medium",
      question:"The minister's speech was so _____ that the audience fell asleep.",
      options:["A) inspiring","B) thought-provoking","C) tedious","D) entertaining"],
      correct:2, explanation:"'Tedious' means long and boring. The result (audience fell asleep) confirms the speech was boring.", trick:"Result-word approach: the effect (fell asleep) tells you the cause (boring = tedious/monotonous)." },

    // ── READING COMPREHENSION STYLE ──
    { source:"PYQ SSC CGL 2022", year:"SSC CGL 2022", topic:"Vocabulary in Context", difficulty:"medium",
      question:"Choose the word most similar to AMELIORATE.",
      options:["A) Worsen","B) Improve","C) Maintain","D) Ignore"],
      correct:1, explanation:"Ameliorate means to make something bad better; to improve.", trick:"SP Bakshi: Ameli = better (French). Synonyms: improve, enhance, rectify, upgrade. Antonym: exacerbate, aggravate." },
    { source:"SP Bakshi — Vocab", year:"SSC CGL 2023", topic:"Vocabulary", difficulty:"hard",
      question:"Choose the antonym of TURPITUDE.",
      options:["A) Virtue","B) Wickedness","C) Depravity","D) Villainy"],
      correct:0, explanation:"Turpitude means wickedness or depravity. Its antonym is Virtue (moral goodness).", trick:"SP Bakshi: Turpitude = moral depravity. Appears in 'moral turpitude'. B, C, D are synonyms. A (virtue) is the antonym." }
  ],

  ga: [
    // ── LUCENT'S GK ── HISTORY
    { source:"Lucent's GK — History", year:"SSC CGL 2023", topic:"Modern History", difficulty:"easy",
      question:"The Indian National Congress was founded in which year?",
      options:["A) 1857","B) 1875","C) 1885","D) 1905"],
      correct:2, explanation:"The Indian National Congress (INC) was founded on 28 December 1885 by A.O. Hume, Dadabhai Naoroji and Dinshaw Wacha.", trick:"Lucent GK: 1885 = INC founded. 1857 = First War of Independence. 1905 = Partition of Bengal." },
    { source:"Lucent's GK — History", year:"SSC CGL 2022", topic:"Ancient History", difficulty:"easy",
      question:"Who wrote the Arthashastra?",
      options:["A) Vatsyayana","B) Chanakya","C) Kalidasa","D) Banabhatta"],
      correct:1, explanation:"Arthashastra, a treatise on statecraft, economic policy and military strategy, was written by Chanakya (also known as Kautilya), advisor to Chandragupta Maurya.", trick:"Lucent GK: Arthashastra=Chanakya, Meghaduta=Kalidasa, Harshcharita=Banabhatta, Kamasutra=Vatsyayana." },
    { source:"Lucent's GK — History", year:"SSC CGL 2021", topic:"Medieval History", difficulty:"medium",
      question:"The Battle of Panipat (First) was fought between Babur and?",
      options:["A) Hemu","B) Ibrahim Lodi","C) Sher Shah Suri","D) Rana Sanga"],
      correct:1, explanation:"The First Battle of Panipat (1526) was between Babur and Ibrahim Lodi. Babur defeated Ibrahim Lodi and established the Mughal Empire.", trick:"Lucent GK: 3 Battles of Panipat — 1st(1526): Babur vs Ibrahim Lodi; 2nd(1556): Akbar vs Hemu; 3rd(1761): Marathas vs Ahmad Shah Abdali." },
    { source:"Lucent's GK — History", year:"SSC CGL 2023", topic:"Freedom Movement", difficulty:"medium",
      question:"'Do or Die' slogan was given during which movement?",
      options:["A) Non-Cooperation Movement","B) Civil Disobedience Movement","C) Quit India Movement","D) Swadeshi Movement"],
      correct:2, explanation:"'Do or Die' (Karo ya Maro) was given by Mahatma Gandhi during the Quit India Movement (1942).", trick:"Lucent GK: Quit India=Do or Die. Simon Commission=Go Back Simon. Non-Cooperation=Non-violent non-cooperation." },

    // ── LUCENT'S GK ── POLITY
    { source:"Lucent's GK — Polity", year:"SSC CGL 2023", topic:"Indian Constitution", difficulty:"easy",
      question:"How many Fundamental Rights are guaranteed by the Indian Constitution?",
      options:["A) 5","B) 6","C) 7","D) 8"],
      correct:1, explanation:"The Indian Constitution guarantees 6 Fundamental Rights: Right to Equality, Right to Freedom, Right against Exploitation, Right to Freedom of Religion, Cultural & Educational Rights, Right to Constitutional Remedies.", trick:"Lucent GK: Originally 7 FRs, Right to Property (Art.31) removed in 1978 by 44th Amendment. Now 6." },
    { source:"Lucent's GK — Polity", year:"SSC CGL 2022", topic:"Indian Constitution", difficulty:"medium",
      question:"Which Article of the Indian Constitution deals with the Right to Education?",
      options:["A) Article 19","B) Article 21","C) Article 21A","D) Article 45"],
      correct:2, explanation:"Article 21A (added by 86th Constitutional Amendment, 2002) provides free and compulsory education for children aged 6-14 years.", trick:"Lucent GK: Art 21=Right to Life, Art 21A=Right to Education, Art 22=Protection against arrest." },
    { source:"Lucent's GK — Polity", year:"SSC CGL 2021", topic:"Parliament", difficulty:"medium",
      question:"The maximum strength of Lok Sabha is?",
      options:["A) 543","B) 545","C) 552","D) 550"],
      correct:2, explanation:"Max strength of Lok Sabha = 552 (530 from states + 20 from UTs + 2 Anglo-Indians, though Anglo-Indian provision was removed in 2020). Current elected strength = 543.", trick:"Lucent GK: Current Lok Sabha=543 elected. Rajya Sabha max=250 (238 elected+12 nominated)." },
    { source:"Lucent's GK — Polity", year:"SSC CGL 2023", topic:"Constitutional Bodies", difficulty:"easy",
      question:"The Election Commission of India was established in?",
      options:["A) 1947","B) 1948","C) 1950","D) 1952"],
      correct:2, explanation:"The Election Commission of India was established on 25 January 1950, one day before India became a Republic.", trick:"Lucent GK: ECI=25 Jan 1950. India became Republic=26 Jan 1950. National Voters' Day=25 Jan." },

    // ── LUCENT'S GK ── GEOGRAPHY
    { source:"Lucent's GK — Geography", year:"SSC CGL 2023", topic:"Indian Geography", difficulty:"easy",
      question:"Which is the longest river in India?",
      options:["A) Godavari","B) Yamuna","C) Ganga","D) Krishna"],
      correct:2, explanation:"The Ganga is the longest river in India with a total length of about 2,525 km.", trick:"Lucent GK: Longest rivers in India — Ganga(2525km) > Godavari(1465km) > Krishna(1400km) > Yamuna(1376km)." },
    { source:"Lucent's GK — Geography", year:"SSC CGL 2022", topic:"World Geography", difficulty:"medium",
      question:"Which is the largest ocean?",
      options:["A) Atlantic Ocean","B) Indian Ocean","C) Pacific Ocean","D) Arctic Ocean"],
      correct:2, explanation:"The Pacific Ocean is the largest and deepest ocean, covering about 165 million km².", trick:"Lucent GK: Size order — Pacific > Atlantic > Indian > Arctic. P-A-I-A. The Pacific is bigger than all land combined." },
    { source:"Lucent's GK — Geography", year:"SSC CGL 2021", topic:"Indian Geography", difficulty:"medium",
      question:"The Tropic of Cancer passes through how many Indian states?",
      options:["A) 6","B) 7","C) 8","D) 9"],
      correct:2, explanation:"Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.", trick:"Lucent GK: Memory — GuRaMa ChJha WeBe TrMi (8 states). Very frequent in SSC." },

    // ── LUCENT'S GK ── SCIENCE
    { source:"Lucent's GK — Science", year:"SSC CGL 2023", topic:"Physics", difficulty:"easy",
      question:"The SI unit of electric current is?",
      options:["A) Volt","B) Watt","C) Ampere","D) Ohm"],
      correct:2, explanation:"The SI unit of electric current is Ampere (A). Volt is unit of potential difference, Watt of power, Ohm of resistance.", trick:"Lucent GK: Electric units — A (Ampere=current), V (Volt=potential), W (Watt=power), Ω (Ohm=resistance)." },
    { source:"Lucent's GK — Science", year:"SSC CGL 2022", topic:"Chemistry", difficulty:"easy",
      question:"What is the chemical formula of common salt?",
      options:["A) NaOH","B) Na₂CO₃","C) NaCl","D) NaHCO₃"],
      correct:2, explanation:"Common salt is Sodium Chloride with formula NaCl.", trick:"Lucent GK: NaCl=common salt, NaOH=caustic soda, Na₂CO₃=washing soda, NaHCO₃=baking soda." },
    { source:"Lucent's GK — Science", year:"SSC CGL 2021", topic:"Biology", difficulty:"medium",
      question:"Which organ of the human body produces bile?",
      options:["A) Pancreas","B) Stomach","C) Liver","D) Kidney"],
      correct:2, explanation:"Bile is produced by the liver and stored in the gallbladder. It aids in digestion of fats.", trick:"Lucent GK: Liver produces bile → stored in gallbladder → released into small intestine. Pancreas produces insulin." },
    { source:"Lucent's GK — Science", year:"SSC CGL 2023", topic:"Physics", difficulty:"medium",
      question:"Which mirror is used as a rear-view mirror in vehicles?",
      options:["A) Plane mirror","B) Concave mirror","C) Convex mirror","D) Parabolic mirror"],
      correct:2, explanation:"Convex mirrors are used as rear-view mirrors because they give a wider field of view and always form erect, diminished images.", trick:"Lucent GK: Convex mirror = diverging = wider view = rear-view. Concave = converging = used in headlights, shaving mirrors." },

    // ── CURRENT AFFAIRS ── (Testbook / Adda247)
    { source:"Testbook Current Affairs 2024", year:"2024", topic:"National Current Affairs", difficulty:"easy",
      question:"New criminal laws BNS, BNSS and BSA came into effect from which date?",
      options:["A) January 1, 2024","B) April 1, 2024","C) July 1, 2024","D) October 1, 2024"],
      correct:2, explanation:"The three new criminal laws — Bharatiya Nyaya Sanhita (BNS), Bharatiya Nagarik Suraksha Sanhita (BNSS), and Bharatiya Sakshya Adhiniyam (BSA) — replaced IPC, CrPC, and Indian Evidence Act from July 1, 2024.", trick:"Testbook: BNS replaces IPC, BNSS replaces CrPC, BSA replaces Evidence Act. Effective July 1, 2024." },
    { source:"Adda247 Current Affairs 2024", year:"2024", topic:"Sports", difficulty:"easy",
      question:"Who won the gold medal in Javelin Throw at Paris Olympics 2024?",
      options:["A) Arshad Nadeem","B) Neeraj Chopra","C) Anderson Peters","D) Jakub Vadlejch"],
      correct:0, explanation:"Arshad Nadeem of Pakistan won gold at Paris Olympics 2024 with a throw of 92.97m. Neeraj Chopra won silver.", trick:"Adda247: Paris 2024 javelin — Arshad Nadeem (Gold, PAK, 92.97m), Neeraj Chopra (Silver, IND, 89.45m)." },
    { source:"Career Power Current Affairs 2024", year:"2024", topic:"Economy", difficulty:"medium",
      question:"India's rank in Global Innovation Index 2024 released by WIPO?",
      options:["A) 35th","B) 39th","C) 42nd","D) 45th"],
      correct:1, explanation:"India ranked 39th in the Global Innovation Index 2024, released by WIPO — India's best ever ranking.", trick:"Career Power: GII 2024 — India 39th (best ever). Switzerland topped the index." },
    { source:"Testbook Current Affairs 2025", year:"2025", topic:"Budget", difficulty:"medium",
      question:"As per Union Budget 2025-26, income up to what amount is tax-free under the new tax regime?",
      options:["A) ₹7 lakh","B) ₹10 lakh","C) ₹12 lakh","D) ₹15 lakh"],
      correct:2, explanation:"Union Budget 2025-26 made income up to ₹12 lakh completely tax-free under the new tax regime (with standard deduction, effectively ₹12.75 lakh for salaried).", trick:"Testbook: Budget 2025-26 headline — zero tax up to ₹12 lakh under new regime. Big change from ₹7 lakh limit." },
    { source:"Adda247 Current Affairs 2024", year:"2024", topic:"Science & Technology", difficulty:"medium",
      question:"India's mission to demonstrate space docking technology is called?",
      options:["A) Gaganyaan","B) Aditya-L1","C) SpaDeX","D) PSLV-C60"],
      correct:2, explanation:"SpaDeX (Space Docking Experiment) is ISRO's mission to demonstrate space docking — a critical technology for future missions including Chandrayaan-4 and Gaganyaan.", trick:"Adda247: SpaDeX = Space Docking Experiment. Launched via PSLV-C60. First Indian docking demonstration." },
    { source:"Lucent's GK", year:"SSC CGL 2022", topic:"Awards & Honours", difficulty:"easy",
      question:"Which is the highest civilian award of India?",
      options:["A) Padma Vibhushan","B) Bharat Ratna","C) Padma Bhushan","D) Padma Shri"],
      correct:1, explanation:"Bharat Ratna is the highest civilian honour of India. The order is: Bharat Ratna > Padma Vibhushan > Padma Bhushan > Padma Shri.", trick:"Lucent GK: Remember BR > PV > PB > PS. 'Ratna' = gem, so highest. Instituted in 1954." },
    { source:"Lucent's GK — Economy", year:"SSC CGL 2022", topic:"Economy", difficulty:"medium",
      question:"NITI Aayog replaced which body in 2015?",
      options:["A) Finance Commission","B) Planning Commission","C) Economic Advisory Council","D) CCI"],
      correct:1, explanation:"NITI Aayog (National Institution for Transforming India) replaced the Planning Commission on 1 January 2015.", trick:"Lucent GK: Planning Commission (est.1950) → replaced by NITI Aayog (Jan 1, 2015). First Chairman = PM Modi." }
  ]
};
